#Author: Christopher Muthi
#Student Number: 21365126
#Acknowlegment of the DCU Academic Integrity Policy:
#
#        I understand that the University regards breaches of academic integrity and plagerism as grave and serious.
#        
#        I have read and understood the DCU Academic Integrity and Plagerism Policy. I accept the penalties that may be imposed should I engage in practice or practices
#        that breach this policy.
#
#        I have identified and included the source of all facts, ideas, opinions and viewpoints of others in the assignment references.
#
#        I delcare that this material, whihc I now submit for assessment, is entirely my own work and has not been taken from the work of others save and to the extent
#        that such work has been cited and acknowledged within teh text of my work.
#
#        I have used the DCU library referencing guidelines and/or the appropriate referencing system recommened in the assignment guidelines and/ore programme
#        documentation.

myshell: myshell.c utility.c myshell.h
	gcc -Wall myshell.c utility.c -o ../bin/myshell
